### ISSUE TITLE
Sign In

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#10]
- [x] Sign in form
- [x] Sign in action flow
- [x] Add user to redux store
- [x] Validation (shared)
- [x] Design
- [x] "Create an account" link should navigate to the sign up page

![sign in](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/c6448f34-8ab7-4b18-acd5-6e055b582dda)

**Comment by MariiaKrasylnykova** [comment]
- Add border for filled fields: 1px all sides; background #F5F7F7 
- Change validation error message for empty fields to: "The field is required"
- Change field color after autocomplete
