### ISSUE TITLE
feat: Chat functionality

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#111]
### What feature?

Add backend for chat functionality. The user can only send messages to their friends.
Create tables, model, service, controller for chats

Note: WebSockets should NOT be implemented. It will be done in a separate ticket.

**Comment by maksym-hladii** [comment]
**FIX:**
- [ ] Error in src/modules/chat-messages/chat-message.controller.ts
