### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#12]
- [x] Form (add first name and last name fields)
- [x] Sign up action flow
- [x] Add user to the redux store
- [x] Validation (shared)
- [x] Design
- [x] Sign in link should navigate to sign in page
- [x] New: Password masking
- [x] New: Fields validation. All fields are required.
- First name - length 2-35, A-Z, a-z, hyphen and apostrophe (one, not first or last);
- Last name - length 2-35, A-Z, a-z, hyphen and apostrophe (one, not first or last);
- Email local part - length 1-35, A-Z, a-z, digits, special characters, dot (not first, last or repeated unless quoted);
- Email domain part - length 3-35, A-Z, a-z, digits, special characters, hyphen and apostrophe (one, not first or last);
- Password: length 8-26, A-Z, a-z, digits, special characters.

![sign up](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/e0534d87-a770-4608-98db-a93741474b75)

**Comment by MariiaKrasylnykova** [comment]
- Change fields' validation error message
- Fix form layout when error messages appear
