### ISSUE TITLE
fix:The Friends page doesn't occupy 100% of the screen height

### ISSUE THREAD

**Issue by MariiaKrasylnykova** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#122]
### Describe your issue

The "Friends" page doesn't occupy 100% of the screen height

### Steps to reproduce

Open the "Friends" page
Delete the friend components
Look at the page

### What was the actual result?

The "Friends" page doesn't occupy 100% of the screen height

### What was the expected result?

The "Friends" page should occupy 100% of the screen height

### Put here any screenshots or videos (optional)

<img width="1202" alt="Attach" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/d0bd0247-4d18-4c74-bae8-98a501e4c8bc">

### What OS are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by MappariChan** [comment]
@GEOFARL also got task with fixing height but height of overview page #121, max fixed it by simply changing styles for overall page container inside of AuthWraper component, so it also works for friends page, so i don't need to fix it anymore.
