### ISSUE TITLE
feat: Friends page mobile responsiveness

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#157]
### What feature?

Add mobile responsiveness to Friends page.

**Comment by maksym-hladii** [comment]
Fix the issues, caused by multiline names:
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/a46f5738-2407-4ef1-bd76-665c84fffdce)
