### ISSUE TITLE
feat: Friends Activity Feed

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#158]
### What feature?

Add Friends Activity Feed screen
We should get the activities of the people we follow
Do not implement like/comment features for now

### Add screenshots

![Friends activity feed](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/654fb711-b569-4cf3-98f9-fdc658e4c3c4)

**Comment by maksym-hladii** [comment]
**FIX:**
- [ ] The "DELETE /activities/finish-section/{id}" controller in Swagger is missing the body
- [ ] The error responses for the controllers in Swagger are missing
