### ISSUE TITLE
fix: The appearance and behavior of the sidebar buttons

### ISSUE THREAD

**Issue by maksym-hladii** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#174]
**FIX:**
- [x] The button, representing the active page, must be a filled button
- [x] The other buttons on the sidebar must be text buttons
- [x] The color of the icons on the filled buttons must be #043730
- [x] The color of the icons on the text buttons must be #F5F7F7
- [x] The color of the icons on the filled buttons after hovering must be #FFFFFF
- [x] The burger button should not turn into an orange square after hovering (screen wirth < 480)
- [x] "Warning: Each child in a list should have a unique "key" prop in Sidebar component"

**Comment by Vfivew** [comment]
![480px](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/55a8cc80-635c-4e39-8a18-3c7d5dfd042f)
![buttons](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/a232fa93-b560-4fa0-85ca-74b621f6818f)
