### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#20]
- [x] Create Header component
- [x] If there is no signed in user, display Sign In button (should navigate to sign-in) and remove chat icon, notification icon and user profile picture
- [x] Add header to the main screen

![header](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/891b64ee-1df2-414d-92d0-b95871c0dec3)

**Comment by MariiaKrasylnykova** [comment]
Remove the "Sign In" button
