### ISSUE TITLE
Add sidebar

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#21]
- [x] Add sidebar to the main screen
- [x] For now add only Overview item

![sidebar](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/f2eb6c97-9926-4f4f-89ca-c2b2573a9743)

**Comment by maksym-hladii** [comment]
- fix the appearance of the logo (icon)
- the logo should be implemented as an image (without using a heading)
