### ISSUE TITLE
feat: Add application schema to readme 

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#213]
### What feature?

Add the application schema using mermaid to the root readme

**Comment by maksym-hladii** [comment]
@fshabanov
We won't be doing something like this?

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/83cccfe4-f652-4966-87f4-47a174e1c2cf)
