### ISSUE TITLE
feat: UAM (User Access Management) - Groups

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#230]
### What feature?

- [x] Create Groups table
- [x] Create Permissions table
- [x] Create Groups to permissions table
- [x] Add possibility to create groups
- [x] Add possibility to edit groups
- [x] Add possibility to delete groups
- [x] To make any changes to groups, user needs to have manage-uam permission

Permissions that we will have - manage-uam, manage-courses, manage-users
Permissions should be checked using Fastify Hooks

**Comment by MariiaKrasylnykova** [comment]
- [ ] Fix controller description in Swagger: GET groups/{userId}/permissions
- [ ] "Edit groups" and "Edit permissions of the group" pop-up windows preserve the previous state
