### ISSUE TITLE
Add welcome section header

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#25]
- [x] Design
- [x] Only display if there is a signed in user

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/a132564a-ed52-446d-92de-b88564ac2625)

**Comment by maksym-hladii** [comment]
- Fix the vertical position of the "Welcome back, <firstName> <lastName>" element
- Fix the width of the component
