### ISSUE TITLE
fix: Default pictures are displayed on the "Friends" page instead of users' profile pictures

### ISSUE THREAD

**Issue by maksym-hladii** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#266]
### Describe your issue

Default pictures are displayed on the user components on the "Friends" page instead of users' profile pictures.

### Steps to reproduce

1. Open the "Trackmates" web application as an authorized user.
2. Navigate to the "Friends" page.
3. Pay attention to the profile pictures of the user on the "Friends" page.

### What was the actual result?

Default pictures are displayed on the user components on the "Friends" page instead of users' profile pictures.

### What was the expected result?

Users' profile pictures are displayed on the user components on the "Friends" page.

### Put here any screenshots or videos (optional)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/3d2cb16e-b10a-4ddf-b3fa-3d2e35149944)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by MariiaKrasylnykova** [comment]
- [ ] fix: The default avatar is displayed incorrectly on the Friends page

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/d511cea3-e19e-48a0-9846-d7ca615068ca)
