### ISSUE TITLE
Course description screen

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#28]
- [x] Fetch the data for a selected course
- [x] Create a screen on frontend and display course data
- [x] Instead of a video player show an image for now

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/db458961-76ce-4ac1-b41b-50181fb0282a)

**Comment by fshabanov** [comment]
@Sytnikovakatya In "About" tab we will have the course description. In "Details" tab we will display all course sections. In the right side we will display first 10 or so sections to avoid a big scroll with an empty left side, when we have lots of sections

**Comment by MariiaKrasylnykova** [comment]
- [ ] fix: Remove the "Back to overview" text near the "Back" button, the "Back" button should navigate to the previous page.
- [ ] fix: Delete the extra space between the image and "About"/"Details" tabs
- [ ] fix: The orange line shouldn't disappear after hovering over active tab
- [ ] fix: The "Read more" link should be gray and become orange after hovering
- [ ] fix: The course title should be gray and doesn't change after hovering
