### ISSUE TITLE
feat: Filter Notifications by type

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#288]
### What feature?

Add a possibility to filter notifications by their type

**Comment by MariiaKrasylnykova** [comment]
The server validation error is shown if there is no notifications type in the URL

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/55293955-6d14-4e94-9502-ce55cbbc8109)
