### ISSUE TITLE
feat: Add pagination to Friends page

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#309]
### What feature?

We should have a pagination in Friends page

**Comment by maksym-hladii** [comment]
**FIX:**
- The number of pages on the "Find friends" tab is greater than it has to be
- Duplicate users are displayed on these pages, in groups smaller than the page limit
- The logic of grouping and sorting is unclear (the users on the video were created sequentially)

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/fd0a8d46-8225-49b3-943a-ab5d058510c5

**Comment by maksym-hladii** [comment]
Implement sorting on the "Find friends" tab by user creation in descending order.
