### ISSUE TITLE
feat: Add Sex dropdown list to the My profile page

### ISSUE THREAD

**Issue by MariiaKrasylnykova** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#343]
### What feature?

- [x] Dropdown list should contain 3 options: Male/Female/Prefer not to say
- [x] Only one option can be selected
- [x] Dropdown list should contain "Select Sex" placeholder

### Add screenshots

<img width="219" alt="Attach 2024-03-05 о 15 40 34" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/25ca7d44-9792-4406-ab9f-627b96a30f99">

**Comment by maksym-hladii** [comment]
Sadly, the field turned out to be too narrow and cuts the bottom part of the letter "y". Make it a little wider, please.
