### ISSUE TITLE
feat: Update the design of the "Chats" page

### ISSUE THREAD

**Issue by maksym-hladii** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#388]
### What feature?

Update the design of the "Chats" page to match the mockup.

### Add screenshots

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/7d459ad3-3d2d-4010-aa65-46ac5f087ad7)

**Comment by GEOFARL** [comment]
In this ticket I will also fix a bug that occurs when we're trying to featch messages from the backed. The users' pictures are not included

**Comment by MariiaKrasylnykova** [comment]
- [ ] Margin should be 0px 0px 10px

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/e5eff9c8-d069-4d36-8059-c36d958c7ad1)

- [ ] Date format should be "Today", "March 7th", "March 4th"

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/1ab5050c-3b09-4a03-b8e1-6ca7b785f9b7)

- [ ] Fix button position

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/2079b6b4-c39b-4b8c-aed5-487fda34cba3)

- [ ] Message background shouldn't depend of the user name and date

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/6a6bfecd-c87d-4c57-baca-83d58df448e7)

- [ ] fix: Messages with line breaks are sent on one row

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/8b5a00ee-f2af-4859-89bf-5a6919b15782)

- [ ] Validation message shouldn't display, user can't send empty messages

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/eb6b3ddc-230d-417f-b977-9e72fbea6616)
