### ISSUE TITLE
Create Friends functionality

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#39]
- [x] Create friends table
- [x] Create model and service
- [x] Add possibility to search for users
- [x] Add possibility to send a request
- [x] Add a possibility to accept/deny request

This task is Backend only

**Comment by maksym-hladii** [comment]
UPDATE:
- [ ] Create friends table
- [ ] Create model and service
- [ ] Add possibility to search for users
- [ ] Add possibility to follow / unfollow a user

This task is Backend only

**Comment by maksym-hladii** [comment]
**FIX:**
- [ ] Swagger warnings
- [ ] Not all users are present on the "Friends" page
