### ISSUE TITLE
feat: Add empty page placeholders

### ISSUE THREAD

**Issue by MariiaKrasylnykova** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#398]
### What feature?

- [x] If there are no added courses on the "Overview" page: 
- the pagination must not be displayed
- the "You haven't added any courses yet" placeholder should be shown
- [x] If there are no potential followers on the "Find friends" tab on the "Friends" page the "There aren't any potential friends" placeholder should be shown
- [x] If there are no followers on the "Followers" tab on the "Friends" page the "You don't have any followers yet" placeholder should be shown
- [x] If there are no following on the "Followings" tab on the "Friends" page the "You aren't following anyone yet" placeholder should be shown
- [x] If there are no notifications on the "Notifications" page the "You don't have any notifications yet" placeholder should be shown
- [x] If there are no activities on the "Activities" page the "There are no activities yet" placeholder should be shown

### Add screenshots

<img width="445" alt="Attach 2024-03-07 о 13 25 48" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/8ae7583d-a7bd-4825-97b1-dd655d5e7c4d">

**Comment by maksym-hladii** [comment]
After the changes made in this task, every time you click the "Follow" / "Following" button, the page reloads. So if the page was scrolled down, a jump up happens. After reloading the page has the previous state: the "Follow" button, which was clicked, remains the "Follow" button, the "Following" button remains the "Following" button. This needs to be fixed.
