### ISSUE TITLE
Add User details screen

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#42]
- [x] Add My Profile screen
- [x] Add a possibility to change name
- [x] Add a possibility to upload an image

![my profile](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/4d952eb0-1af7-4896-ab4f-05db7736faf4)

**Comment by MariiaKrasylnykova** [comment]
- [ ] Cancel and Update buttons should be as designed and become #F76519 after hovering
- [ ] Cancel button allows the user to undo all changes made
- [ ] The user is prevented from leaving the page without saving the changes — the "Changes are not saved.” message appears as a toast-message. 
- [ ] If the changes are successfully saved, the “Changes are saved.” message appears as a toast-message.
- [ ] User foto on the header should repeat profile foto's styles

**Comment by maksym-hladii** [comment]
**FIX:**
- [ ] The "Unexpected token '<', "<!doctype "... is not valid JSON" error when trying to update the profile in the deployed app
- [ ] Rectangular photos distort the "Profile" icon on the header and the profile picture on the "Profile" page
