### ISSUE TITLE
fix: Response code 200 / 304 instead of 404 when the requested resource is not found, in particular on the "Page Not Found" page

### ISSUE THREAD

**Issue by maksym-hladii** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#426]
### Describe your issue

When the requested resource is not found, the response code is 200 or 304 instead of 404, in particular on the "Page Not Found" page.

### Steps to reproduce

1. Try to open a non-existing page.
2. Check the response code, using DevTools.

### What was the actual result?

When the requested resource is not found, the response code is 200 if the cache is disabled and 304 if the cache is enabled.

### What was the expected result?

When the requested resource is not found, the response code is 404.

### Put here any screenshots or videos (optional)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/2be87b49-3227-4df7-b08c-c701cf0a6c7b)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome, Firefox

### Severity

Trivial (S5)

**Comment by fshabanov** [comment]
It won't be done
