### ISSUE TITLE
fix: The "Follow" / "Following" buttons on user components are not updated on the new tab after following / unfollowing the users

### ISSUE THREAD

**Issue by MariiaKrasylnykova** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#444]
### Describe your issue

The "Follow" / "Following" buttons on user components are not updated on the new tab of the "Friends" page after following / unfollowing the users. This bug appeared after the changes made here: https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/commit/59e96c504d771ac6bbda585c0b25c1f528b974f6 https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/commit/71fb45d3acba7972b7aedd4e9c54566d7f9dcf53

### Steps to reproduce

1. Open the app as an authorized user.
2. Click the "Friends" button on the sidebar.
3. Switch to the "Followings" tab on the "Friends" page.
4. Click the "Following" button on a user component to unfollow the user.
5. Switch to the "Find friends" tab.
6. Find the same user component.
7. Pay attention to the button on the component.

### What was the actual result?

The "Following" button is displayed on the user component on the "Find friends" tab after unfollowing them on the "Followings" tab.

### What was the expected result?

The "Follow" button is displayed on the user component on the "Find friends" tab after unfollowing them on the "Followings" tab.

### What OS are you seeing the problem on?

Windows, MacOS

### What browsers are you seeing the problem on?

Chrome

### Severity

Major (S3)

**Comment by maksym-hladii** [comment]
**FIX:**
- [ ] Followers, who are followed by the current user, are displayed with "Follow" buttons instead of "Following" buttons on the "Followers" tab

**Comment by maksym-hladii** [comment]
The problem is still relevant:
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/350132ff-1d94-4cf5-bca2-673fec76e4f7
