### ISSUE TITLE
feat: Update the design of the "Notifications" page

### ISSUE THREAD

**Issue by MariiaKrasylnykova** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#447]
### What feature?

Update the design of the "Notifications" page to match the mockup

### Add screenshots

<img width="594" alt="Attach 2024-03-13 о 04 35 46" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/a173ccf7-73ec-460b-adef-73a5f94821f5">

**Comment by maksym-hladii** [comment]
Implement one more little update, please:

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/12c70512-00fb-4ed2-aa10-2fbd6d31a8dd)
