### ISSUE TITLE
feat: Forgot Password

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#499]
### What feature?

Add a possibility to change password if user forgot it

**Comment by maksym-hladii** [comment]
**FIX:**
- [x] There is an extra slash at the end of the UPDATE_PASSWORD_LINK line, which makes the recovery link invalid
- [x] The "Lowercase and uppercase Latin letters, digits, special characters are allowed !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~" rule for the "Password" field on the "Update password" form is missing
