### ISSUE TITLE
Sign In screen mobile responsiveness

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#56]
- [x] Add mobile responsiveness to the Sign In screen

**Comment by MariiaKrasylnykova** [comment]
Fix the mobile design
Add the placeholders: 
- the Email field should display the “email@gmail.com” placeholder
- the Password field should display eight dots as placeholder

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/a2766eeb-8fca-4665-9b90-76421a21dbdb)
