### ISSUE TITLE
Sign up screen mobile responsiveness

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#57]
- [x] Add mobile responsiveness to Sign up screen

**Comment by fshabanov** [comment]
Will be done within #56

**Comment by MariiaKrasylnykova** [comment]
Fix the mobile design
Add the placeholders:
- the First name field should display "First name" placeholder
- the Last name field should display "Last name" placeholder
- the Email field should display the “email@gmail.com” placeholder
- the Password field should display eight dots as placeholder

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/6f6b6652-7708-4c49-b80b-d8dfcbac714d)
