### ISSUE TITLE
Overview screen mobile responsiveness

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#61]
- [x] Add mobile responsiveness for the Overview screen
- [x] Add responsiveness to the header component
- [x] Add responsiveness to the Welcome section

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/748f7007-11e8-41b7-91f7-4b342e38e819)

**Comment by MariiaKrasylnykova** [comment]
- Fix: if the name of the user is shown in two rows in the welcome section, the letters in the second row are cropped on the all resolutions
- Fix: the welcome character is shown not in the centre of the welcome section between 1150-820 px screen width resolution
- Fix: the header is shown side by side with welcome section without extra space after changing width resolution to 1024 px and less
- Fix: Header mobile responsiveness
- Fix: Course section mobile responsiveness

Mockup:

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/eedd4cb9-ec52-4df3-9bea-8ba05611dd31)

**Comment by MariiaKrasylnykova** [comment]
Fix: Header mobile responsiveness (480px)
Fix: Course section mobile responsiveness (width 1024px; 480px)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/9151c4e1-31e5-4a0c-9c2b-d09d21ae0b26)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/159526421/697c9441-b712-46f6-99bb-15c622bd620e)
