### ISSUE TITLE
feat:  Add pagination to the Activities page

### ISSUE THREAD

**Issue by MariiaKrasylnykova** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#646]
### What feature?

We should have a pagination on the Activities page

**Comment by maksym-hladii** [comment]
Fix the error appearing on the "Activities" page:
![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/d6fd1517-2f02-458f-a8f4-7911cb191599)
