### ISSUE TITLE
Create Udemy module

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#65]
We will use [Udemy API](https://www.udemy.com/developers/affiliate/) to get courses
- [x] Create Udemy module
- [x] We should be able to search courses by course name
- [x] We should be able to get details for a specific course

**Comment by KrasKa2** [comment]
@fshabanov do you have an Affiliate API ClientId?
I have tried to get this id in Friday, and it was disapproved:
<img width="1102" alt="Screenshot 2024-02-13 at 10 04 58" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/153290443/2bf0a8e9-079c-4225-996a-c2abad3b96bc">
