### ISSUE TITLE
feat: Update app logo

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#78]
### What feature?

Our app logo was updated. Update it in each screen, where the old one is used

### Add screenshots

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/fc3bdfa6-c705-4c2d-84f0-aebe77fe299c)

**Comment by MariiaKrasylnykova** [comment]
Fix the position of the logo

**Comment by MariiaKrasylnykova** [comment]
Fix the logo. It should be implemented as one image (without text!!!)
