### ISSUE TITLE
feat: Create Friend component

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-winter-2023-2024-trackmates#82]
### What feature?

- [ ] Create Friend component
- [ ] Create Friends screen and display component there

### Add screenshots

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/3183ac19-ee6a-4ac2-bf30-ec0d1fa39498)

**Comment by maksym-hladii** [comment]
### UPDATE:

### What feature?

- [ ] Create Friend component
- [ ] Create Friends screen and display component there

### Add screenshots

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/66385d6b-37c5-4a1f-9c36-e68815b5d5e0)

**Comment by maksym-hladii** [comment]
fix:
- [ ] Component background should be white
- [ ] Component should react to hovering
- [ ] The "Follow" label color should be #043730
- [ ] The first and last name color should be #313134

**Comment by maksym-hladii** [comment]
FIX:
- [ ] Square shadows of the component (Screenshot №1)
- [ ] White square bottom left corner when hovering the component (Screenshot №2)
- [ ] The component should not have white outline
- [ ] The "Follow" button appearance should change according to the design (when hovering)
- [ ] The first and last name font should be Roboto
- [ ] The font of the "Follow" label should be Roboto

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/172221a9-de6c-46c9-a2f2-85fafe3bbbec)

![Image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/34922862/4c734c1d-fc75-499d-8efe-d3d0822f1b0c)

**Comment by maksym-hladii** [comment]
Update the appearance and behavior of the "Follow" / "Following" button after hovering according to the clarified design.

**Comment by GEOFARL** [comment]
This component is a part of the friends page task #94, so I'll make all the fixes on that branch
